port = 50051
DB {
  host = "nas.pauel"
  port = 5432
  name = "NuclearOption_Testing"
}
discord {
  token = "YOUR TOKEN HERE"
  serverChannels = [
    {
      publicChat = 1481697022686920847
      privateChat = 1481697065292664943
    }
  ]
  teamKillChannel = 1354932451213836460
}