port = 50051
DB {
  host = "postgres"
  port = 5432
  name = "Central"
  user = "postgres"
  password = "YOUR_PASSWORD_HERE"
}
discord {
  token = "YOUR TOKEN HERE"
  enable = true
  guildID = 989821370747719731
  statusChannel = 989821371280400437
  serverWebhooks = [
    {
      publicChat = "https://discord.com/api/webhooks/1494656961000636540/G7A8z2_8r7PkevtDkpVkEtCK6XUrNBzsKZIUXeB8QFlGmh2qYEhfv0LRGVhySpkJYqqK"
      privateChat = "https://discord.com/api/webhooks/1494656961000636540/G7A8z2_8r7PkevtDkpVkEtCK6XUrNBzsKZIUXeB8QFlGmh2qYEhfv0LRGVhySpkJYqqK"
    }
  ]
  teamKillWebhook = "https://discord.com/api/webhooks/1494656961000636540/G7A8z2_8r7PkevtDkpVkEtCK6XUrNBzsKZIUXeB8QFlGmh2qYEhfv0LRGVhySpkJYqqK"
  moderatorRole = 1420006950707658783
  adminRole = 1419708521053818974
  linkedRole = 1354932527902752869 // Linked player
}
api{
  baseUrl: "https://testapi.silly-club.rodeo"
  port: 8069
  steam {
    callbackPath = "/auth/steam/callback"
  }
  jwt {
    secret = "SUPER_AWESOME_SECRET_THAT_IS_NOT_YET_LONG_ENOUGH_BUT_SOON_™_WILL_BE"
    issuer = "gw-api-testing"
    audience = "gw-users-testing"
    validityMs = 86400000 // One day
  }
}