port = 50051
DB {
  host = "nas.pauel"
  port = 5432
  name = "NuclearOption_Testing"
  user = "pauel"
  password = ""
}
discord {
  token = "YOUR TOKEN HERE"
  enable = true
  serverChannels = [
    {
      publicChat = 1481697022686920847
      privateChat = 1481697065292664943
    }
  ]
  teamKillChannel = 1354932451213836460
  adminRoles = [
    993194825316827256, // Role on my testing server; TODO remove at end of testing
    1419708521053818974, // Admin role on GW server
    1420006950707658783, // Mod role on GW server
    1419708388421406801 // Dev role on GW server
  ]
}
api{
  baseUrl: "https://testapi.silly-club.rodeo"
  steam {
    callbackPath = "/auth/steam/callback"
  }
  jwt {
    secret = "SUPER_AWESOME_SECRET_THAT_IS_NOT_YET_LONG_ENOUGH_BUT_SOON_™_WILL_BE"
    issuer = "gw-api-testing"
    audience = "gw-users-testing"
    validityMs = 86400000 // One day
  }
}