syntax = "proto3";

package com.graywar.noServerManager.proto;



option java_multiple_files = true;
option java_package = "com.graywar.noServerManager.proto";


import "google/protobuf/timestamp.proto";

// ---------------------------------------------------------------------
// Messages
// ---------------------------------------------------------------------

message StatusRequest {
  string agent_id      = 1;   // e.g. hostname or Docker container id
  google.protobuf.Timestamp last_heartbeat = 3;
}

message StatusResponse {
  bool ok = 1;
}


message AgentInfo{
  string agentID = 1;
}

message BanRequest {
  bool shouldBeBanned = 1;
  uint64 steamID = 2;
  string reason = 3;
  google.protobuf.Timestamp ban_start = 4;
  google.protobuf.Timestamp ban_end = 5;
  string agentID = 6;
}

message ChatLog{
  google.protobuf.Timestamp messageSendTime = 1;
  string messageChannel = 2;
  string message = 3;
}

message ChatLogs{
  repeated ChatLog logs = 1;
}

message Ack {
  bool ok = 1;
}



// ---------------------------------------------------------------------
// Services
// ---------------------------------------------------------------------

service EdgeAgentService {
  // The edge agent calls this to report its status.
  rpc ReportStatus(StatusRequest) returns (StatusResponse);
  rpc SendBan(BanRequest) returns (Ack);
  rpc SendChatLogs(ChatLogs) returns (Ack); // TODO make stream

  rpc SubscribeToBans(AgentInfo) returns (stream BanRequest);
}
